import Footer from "./common/layout/footer/Footer";
import Header from "./common/layout/header/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
        <nav>
          <Header/>
        </nav>
        <main className="h-full">{children}</main>
        <footer className="shadow-lg h-full w-full bg-footer text-footer-text">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
